"use client";

import { useState } from "react";
import { DAYS, PERIODS, createSeedProblem, generateSchedule, type ScheduleEntry, type ScheduleProblem, type ScheduleResult } from "@/lib/scheduler";
import styles from "./page.module.css";

const emptyResult: ScheduleResult = { success: false, entries: [], diagnostics: [], stats: { requiredPeriods: 0, assignedPeriods: 0, searchNodes: 0, durationMs: 0 } };

export default function Home() {
  const [problem, setProblem] = useState<ScheduleProblem>(() => createSeedProblem());
  const [result, setResult] = useState<ScheduleResult>(emptyResult);
  const [view, setView] = useState<"division" | "faculty" | "room">("division");
  const [selectedId, setSelectedId] = useState("cs-a");
  const [isGenerating, setIsGenerating] = useState(false);
  const options = view === "division" ? problem.divisions.map((item) => ({ id: item.id, label: item.name })) : view === "faculty" ? problem.faculty.map((item) => ({ id: item.id, label: item.name })) : problem.rooms.map((item) => ({ id: item.id, label: item.name }));
  const activeId = options.some((item) => item.id === selectedId) ? selectedId : options[0]?.id ?? "";
  const visibleEntries = result.entries.filter((entry) => view === "division" ? entry.divisionId === activeId : view === "faculty" ? entry.facultyId === activeId : entry.roomId === activeId);
  const lookup = (entry: ScheduleEntry) => ({ subject: problem.subjects.find((item) => item.id === entry.subjectId), division: problem.divisions.find((item) => item.id === entry.divisionId), faculty: problem.faculty.find((item) => item.id === entry.facultyId), room: problem.rooms.find((item) => item.id === entry.roomId) });
  const handleGenerate = () => { setIsGenerating(true); window.setTimeout(() => { setResult(generateSchedule(problem)); setIsGenerating(false); }, 120); };
  const handleSeed = () => { setProblem(createSeedProblem()); setResult(emptyResult); setSelectedId("cs-a"); setView("division"); };
  const errorCount = result.diagnostics.filter((item) => item.severity === "error").length;
  const warningCount = result.diagnostics.filter((item) => item.severity === "warning").length;

  return (
    <main className={styles.shell}>
      <header className={styles.topbar}><div className={styles.brand}><div className={styles.brandMark}>IT</div><div><p className={styles.eyebrow}>Academic operations</p><h1>Intelligent Timetable Generator</h1></div></div><div className={styles.topbarMeta}><span className={styles.statusDot} /> <span>Constraint engine ready</span><span className={styles.version}>v1.0</span></div></header>
      <section className={styles.hero}><div><p className={styles.kicker}>Assignment 3 / Scheduling workspace</p><h2>Build a week that holds together.</h2><p className={styles.heroCopy}>Resolve faculty, room, and division constraints in one deterministic pass. Every generated slot is explainable.</p></div><div className={styles.heroActions}><button className={styles.secondaryButton} onClick={handleSeed}>Reset seed data</button><button className={styles.primaryButton} onClick={handleGenerate} disabled={isGenerating}><span className={styles.buttonGlyph}>{isGenerating ? "..." : "+"}</span>{isGenerating ? "Generating" : "Generate timetable"}</button></div></section>
      <section className={styles.metrics} aria-label="Schedule metrics"><Metric label="Required periods" value={result.stats.requiredPeriods || 54} detail="Across all divisions" /><Metric label="Scheduled" value={result.stats.assignedPeriods} detail={result.success ? "All constraints satisfied" : "Awaiting generation"} accent={result.success ? "green" : undefined} /><Metric label="Search nodes" value={result.stats.searchNodes || "--"} detail={result.stats.durationMs ? `${result.stats.durationMs} ms solve time` : "Deterministic backtracking"} /><Metric label="Diagnostics" value={errorCount + warningCount} detail={`${errorCount} errors / ${warningCount} warnings`} accent={errorCount ? "red" : undefined} /></section>
      <div className={styles.contentGrid}>
        <aside className={styles.sidebar}><div className={styles.panelHeading}><div><p className={styles.sectionLabel}>Control center</p><h3>Plan inputs</h3></div><span className={styles.readyPill}>Seeded</span></div><SetupSection title="Divisions" count={problem.divisions.length} items={problem.divisions.map((item) => `${item.name} / ${item.studentCount} students`)} /><SetupSection title="Faculty" count={problem.faculty.length} items={problem.faculty.map((item) => `${item.name} / ${item.maxWeeklyPeriods} weekly max`)} /><SetupSection title="Rooms & labs" count={problem.rooms.length} items={problem.rooms.map((item) => `${item.name} / ${item.type}`)} /><SetupSection title="Subjects" count={problem.subjects.length} items={problem.subjects.map((item) => `${item.name} / ${item.weeklyPeriods} periods`)} /><div className={styles.preflight}><div className={styles.preflightTitle}><span className={styles.checkMark}>{errorCount ? "!" : "OK"}</span> Pre-validation</div><p>{result.diagnostics.length ? `${errorCount + warningCount} diagnostic${errorCount + warningCount === 1 ? "" : "s"} returned by the engine.` : "Ready to check capacity and constraints."}</p><div className={styles.capacityTrack}><span style={{ width: "60%" }} /></div><small>54 / 90 total room-period capacity</small></div></aside>
        <section className={styles.workspace}><div className={styles.workspaceHeader}><div><p className={styles.sectionLabel}>Generated schedule</p><h3>Weekly matrix</h3></div><div className={styles.filters}><select value={view} onChange={(event) => { const nextView = event.target.value as typeof view; setView(nextView); setSelectedId(nextView === "division" ? "cs-a" : nextView === "faculty" ? "f-aisha" : "room-101"); }} aria-label="Schedule view"><option value="division">By division</option><option value="faculty">By faculty</option><option value="room">By room</option></select><select value={activeId} onChange={(event) => setSelectedId(event.target.value)} aria-label="Schedule selection">{options.map((option) => <option key={option.id} value={option.id}>{option.label}</option>)}</select></div></div>
          {result.diagnostics.length > 0 && <div className={styles.diagnostics}>{result.diagnostics.map((diagnostic, index) => <div className={diagnostic.severity === "error" ? styles.errorBanner : styles.warningBanner} key={`${diagnostic.message}-${index}`}><strong>{diagnostic.severity === "error" ? "Blocked" : "Review"}</strong><span>{diagnostic.message}</span></div>)}</div>}
          <div className={styles.matrixWrap}><div className={styles.matrix}><div className={styles.cornerCell}><span>Day / period</span></div>{PERIODS.map((period) => <div className={styles.periodHeader} key={period}><span>P{period}</span><small>{period === 1 ? "08:00" : `${7 + period}:00`}</small></div>)}{DAYS.map((day, dayIndex) => <div className={styles.matrixRow} key={day}><div className={styles.dayLabel}><strong>{day}</strong><span>{dayIndex + 1}</span></div>{PERIODS.map((period) => { const entry = visibleEntries.find((item) => item.day === dayIndex && item.period === period); const details = entry ? lookup(entry) : null; return <div className={`${styles.slot} ${entry ? styles.filledSlot : ""}`} key={`${day}-${period}`}>{details ? <><strong>{details.subject?.name}</strong><span>{view === "division" ? details.room?.name : details.division?.name}</span><small>{details.faculty?.name?.replace("Prof. ", "")}</small></> : <span className={styles.emptySlot}>Open</span>}</div>; })}</div>)}</div></div><div className={styles.legend}><span><i className={styles.legendFilled} /> Scheduled slot</span><span><i className={styles.legendOpen} /> Available</span><span className={styles.matrixNote}>{visibleEntries.length} visible assignments</span></div>
        </section>
      </div>
      <footer className={styles.footer}><span>Deterministic backtracking CSP</span><span>5 days / 6 periods / hard constraints enforced</span><span>Last run: {result.success ? "Successful" : "Not generated"}</span></footer>
    </main>
  );
}

function Metric({ label, value, detail, accent }: { label: string; value: number | string; detail: string; accent?: "green" | "red" }) { return <div className={styles.metric}><span className={styles.metricLabel}>{label}</span><strong className={accent === "green" ? styles.greenValue : accent === "red" ? styles.redValue : ""}>{value}</strong><span className={styles.metricDetail}>{detail}</span></div>; }

function SetupSection({ title, count, items }: { title: string; count: number; items: string[] }) { return <details className={styles.setupSection} open><summary><span>{title}</span><b>{count}</b></summary><div className={styles.setupItems}>{items.map((item) => <span key={item}>{item}</span>)}</div></details>; }
